@startuml
'skinparam dpi 250'
skinparam classBackgroundColor #F8F8F8
skinparam classBorderColor #0066CC
skinparam classArrowColor #0066CC

class Paystation {
  	- amountToPay : int
        - currentSelectPumpId : int
        - returnMoney : int
  	- createQuittance()
  	+ ReturnBackMoney()
  	+ SetAmountToPay(ppumpId : int)
  	+ PayMoney(pworth : int)
  	+ PayStation()
}

class PetrolPump {
        - petrolPumpId : int
        - tankspeed : int
        - amountToPlay : int
        + AddTap(ptap : Tap)
        + SetId(ppumpId : int)
        + GetId() : int
	+ UnlockTaps() 
	+ GetAmountToPay() : decimal
	+ Fuelling(ptap : Tap) 
        + PetrolPump()
}
note right : Controls the access to the Taps,\nthe fuelling operation and the amount\n to pay at this pump\n 

class Tap {
       - fuellingMethod : Action
        - locked : boolean
	+ Take()
        + Lock() 
        + Unlock()
        + DecreaseFuelLevelOfTank(pamount : int)
        + GetPricePerLiter() : int
        + GetFuelTypeName() : string
        + Tap(pfuellingMethode : Action, pfuelTank : FuelTank)
}
note bottom: When Take() method called,\n it will calls the fuellingMethod,\nwhich contains the Fuelling Method of his PetrolPump \nand overgives himself to ther\nlook at \nhttp://stackoverflow.com/questions/7923343/delegate-with-parameters-as-a-parameter

class FuelTank {
	- maxLevel : int
	- fuelLevel : int
	- lowCriticalVolumePercent : decimal
	- highCriticalVolumePercent : decimal
	+ DecreaseFuelLevel(pamount) : void 
        + GetPricePerLiter() : int
        + GetFuelTypeName() : string
        + FuelTank(pmaxLevel : int, plowCriticalVolumePercent : decimal,  phighCriticalVolumePercent : decimal, pfuelType : Fueltype)
}

class Fueltype {
	- name : string
	- pricePerLiter : decimal
        - GetPricePerLiter() : int 
        - GetName() : string
}
note top : maybe it is a good idea to \nimplement this as a struct

class Quittance {
	- createdAt : datetime
	- amountToPay : int
	+ Quittance(amountToPay : datetime, createdAt : datetime)
}

class PumpController {
	- instance : PumpController
	- pumps : List<PetrolPump>
	- PumpController()
	+ AddPump(ppetrolPump : PetrolPump)
	+ GetInstance() : PumpController
	+ ResetAndUnlockPump(ppumpId : int) 
	+ GetAmountToPay(ppumpId : int) : int
}
note right: This is a Singleton

class MoneyContainer {
  - lowCriticalPercent : decimal
  - maxCriticalPercent : decimal
  - maxCount : int
  - count : int
  - worth : decimal
  + GetWorth() : decimal
  + IncreaseCount()
  + DecreaseCount()
  + MoneyContainer(pworth : int, pcount : int,\npmaxCount : decimal, maxCritPercent : int, lowCritPercent : decimal)
  + CheckCiticalPercent() 
  
}
note left: coinWorth is in fr

class DataContainer {
	+ Load()
	+ Save()
}
note right: Controlls the acces to the stored data

PumpController "1" --* "*" PetrolPump
Paystation ...right....> PumpController : Calls
Paystation "1" -right-* "*" MoneyContainer
Paystation .up.> Quittance : creates
PetrolPump "1" --* "*" Tap
Tap "*" -right-* "1" FuelTank
FuelTank "*" -right-* "1" Fueltype

Tap .up.> PetrolPump : Take() calls Fuelling() as delegate
@enduml 
